language: node_js
node_js: node

env:
  global:
    # - NETLIFY_AUTH_TOKEN is specified in the UI elsewhere
    - NETLIFY_SITE_ID=e5b3d64d-7241-4bea-a328-31aee9a3b722

branches:
  only:
    - master

git:
  clone: false

cache:
  yarn: true

  directories:
    - .cache
    - public


install: yarn
script:
  - yarn build
  - yarn netlify deploy --prod --auth $NETLIFY_AUTH_TOKEN

