language: node_js
node_js: node

env:
  global:
    # - NETLIFY_AUTH_TOKEN is specified in the UI elsewhere
    - NETLIFY_SITE_ID=e5b3d64d-7241-4bea-a328-31aee9a3b722

branches:
  only:
    - master

git:
  clone: false

cache: yarn

before_install:
  - yarn global add netlify-cli
  - git clone https://github.com/ludobrew/core.git
  - git clone https://github.com/ludobrew/game-exalted-3e.git
  - git clone https://github.com/Everspace/personal-ludobrew.git
  - "echo '{ \"name\": \"my-workspace\",\"private\": true, \"workspaces\": [\"core\", \"game-exalted-3e\", \"personal-ludobrew\" ] }' > package.json"

install: yarn
script:
  - yarn workspace personal-ludobrew build
  - netlify deploy --dir=personal-ludobrew/public --prod --auth $NETLIFY_AUTH_TOKEN
