language: node_js
node_js: node

env:
  global:
    # - NETLIFY_AUTH_TOKEN is specified in the UI elsewhere
    - NETLIFY_SITE_ID=e5b3d64d-7241-4bea-a328-31aee9a3b722

branches:
  only:
    - main

git:
  clone: false

cache:
  yarn: true
  directories:
    - .cache
    - public
    - node_modules
    - core_node_modules
    - exalted-3e_node_modules
    - brew_node_modules

before_install:
  - yarn global add netlify-cli
  - git clone -q --depth 1 https://github.com/ludobrew/gatsby-theme-ludobrew-core.git -b main
  - git clone -q --depth 1 https://github.com/ludobrew/gatsby-theme-ludobrew-exalted-3e.git -b main
  - git clone -q --depth 1 https://github.com/Everspace/ludobrew-exalted-3e.git -b main
  - mv core_node_modules       gatsby-theme-ludobrew-core/node_modules
  - mv exalted-3e_node_modules gatsby-theme-ludobrew-exalted-3e/node_modules
  - mv brew_node_modules       ludobrew-exalted-3e/node_modules
  - >-
      echo
      '{
        "name": "my-workspace",
        "private": true,
        "workspaces": [
          "gatsby-theme-ludobrew-core",
          "gatsby-theme-ludobrew-exalted-3e",
          "ludobrew-exalted-3e"
        ]
      }'
      > package.json

install: yarn
script:
  - ls
  - mv .cache public ./ludobrew-exalted-3e/
  - yarn workspace ludobrew-exalted-3e build
  - mv ./ludobrew-exalted-3e/.cache ./ludobrew-exalted-3e/public .
  - mv gatsby-theme-ludobrew-core/node_modules       core_node_modules
  - mv gatsby-theme-ludobrew-exalted-3e/node_modules exalted-3e_node_modules
  - mv ludobrew-exalted-3e/node_modules              brew_node_modules
  - netlify deploy --dir=./public  --prod --auth $NETLIFY_AUTH_TOKEN
